# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='puerto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
